Github: tell reporter where repository is

diff --git a/.github/workflows/ConfiguratorTests.yml b/.github/workflows/ConfiguratorTests.yml
--- a/.github/workflows/ConfiguratorTests.yml
+++ b/.github/workflows/ConfiguratorTests.yml
@@ -30,15 +30,15 @@ jobs:
       - name: Fetch Repository
         uses: actions/checkout@v4
         with:
-          path: 'ratos-configuration'
-          
+          path: "ratos-configuration"
+
       - name: Fetch Configurator Repository
         uses: actions/checkout@v4
         with:
-          path: 'ratos-configurator'
+          path: "ratos-configurator"
           repository: Rat-OS/RatOS-configurator
           ref: ${{ github.ref_name }}
-          
+
       - name: Setup Node.js environment
         uses: actions/setup-node@v4.0.1
         with:
@@ -69,15 +69,16 @@ jobs:
       - name: Install all dependencies
         working-directory: ratos-configurator/src
         run: pnpm install --frozen-lockfile
-            
+
       - name: Run configuration tests
         working-directory: ratos-configurator/src
         run: pnpm run test:ci:config --outputFile=./report.xml
 
       - name: Test Report
         uses: dorny/test-reporter@v1
-        if: success() || failure()    # run this step even if previous step failed
+        if: success() || failure() # run this step even if previous step failed
         with:
-          name: JEST Tests            # Name of the check run which will be created
-          path: report.xml    # Path to test results
-          reporter: jest-junit        # Format of test results
+          name: JEST Tests # Name of the check run which will be created
+          path: report.xml # Path to test results
+          reporter: jest-junit # Format of test results
+          working-directory: ratos-configurator
